In [74]:
import pandas as pd
import numpy as np
import math
from sklearn import linear_model

In [18]:
df = pd.read_csv("test_scores.csv")
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [30]:
x = np.array(df.math)
y = np.array(df.cs)

In [23]:
x

array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67], dtype=int64)

In [24]:
y

array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73], dtype=int64)

In [41]:
gradient_descent(x,y)

m 7913.440000000001, b -111.84000000000002, cost 5199.1, iteration 0
m -59911779.59680001, b 845385.8432000004, cost 296258583436.4736, iteration 1
m 453645524672.924, b -6401173111.953667, cost 1.6985555255513227e+19, iteration 2
m -3434954859167804.0, b 48468990626839.2, cost 9.738421213742959e+26, iteration 3
m 2.600910676470326e+19, b -3.670019559722253e+17, cost 5.583382250956818e+34, iteration 4
m -1.969381440027494e+23, b 2.778899125925957e+21, cost 3.201151056837257e+42, iteration 5
m 1.4911943310518434e+27, b -2.104152369328645e+25, cost 1.8353334283953437e+50, iteration 6
m -1.129116222873569e+31, b 1.593241421412185e+29, cost 1.0522617438470517e+58, iteration 7
m 8.549545945879483e+34, b -1.2063851762377033e+33, cost 6.032989757790907e+65, iteration 8
m -6.473623742176005e+38, b 9.134618105497772e+36, cost 3.45892698565124e+73, iteration 9


In [29]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,9,11,13])

In [83]:
reg = linear_model.LinearRegression()
reg.fit(df[['math']], df['cs'])

LinearRegression()

array([1.01773624])

1.9152193111568891

In [90]:
gradient_descent(x,y,reg.coef_,reg.intercept_)

m 2.96754e-16, b -4.1939999999999994e-18, m1 [1.01773624], b1 1.9152193111568891, cost 5199.099999999999, iteration 2


In [89]:
def gradient_descent(x,y,x1,y1):
    m_curr = b_curr = 0
    iterations = 10
    n = len(x)
    learning_rate = 1e-20
    prev_cost = 0
    for i in range(iterations):
        y_predicted = m_curr * x + b_curr
        cost = (1/n)*sum([val**2 for val in (y-y_predicted)])
        md = -(2/n)*sum(x*(y-y_predicted))
        bd = (2/n)*sum(y-y_predicted)
        m_curr = m_curr - learning_rate * md
        b_curr = b_curr - learning_rate * bd
        if (i > 1 and math.isclose(prev_cost, cost)):
#             print("prev_cost {}, cost {}".format(prev_cost,cost))
            print("m {}, b {}, m1 {}, b1 {}, cost {}, iteration {}".format(m_curr,b_curr,x1,y1,cost,i))            
            break
        prev_cost = cost


m 9.8918e-17, b -1.398e-18, cost 5199.1, iteration 0
m 1.97836e-16, b -2.796e-18, cost 5199.099999999999, iteration 1
prev_cost 5199.099999999999, cost 5199.099999999999


LinearRegression()

array([1.01773624])

1.9152193111568891